### ISSUE TITLE
Custom Glaemscrafu font name issue

### ISSUE THREAD

**Issue by Omikhleia** [BenTalagan/glaemscribe#1]
Font SaratiEldamarRTLBarGlaemscrafu.ttf (for instance, not check with other fonts yet) installs on Windows as "Sarati Eldamar RTL Bar", i.e. the same name as the original Sarati Eldamar RTL Bar, prompting for its replacement on the system. Some users might want to keep the original font for other applications.

**Comment by BenTalagan** [comment]
Hey mighty Dragon,

Should already have been fixed, this is my mistake : I forgot to update the fonts during the last update of the website. This is fixed now and I removed the sfd files (they were completely unuseful).
