### ISSUE TITLE
Other Pustar punctuation

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#11]
Should we address these `Quadruple Pusta, Squared Quadruple Pusta, Quintuple Pusta`  which are included in FreeMonoTengwar, Elfica and Eldamar, but not in Annatar and others? I mean the fonts, not the charsets.

![dots](https://user-images.githubusercontent.com/1594982/26967321-fe465454-4d27-11e7-9c06-97bdd46cc021.png)
P/S: Elfica doesn't have the middle one, `Squared Quadruple Pusta`.

**Comment by BenTalagan** [comment]
Copy/Pasting my answer from #10 : 😃 

Good question. My general thought about this is to stay close to what is attested in Tolkien's works atm. Generally speaking, it means that my current reference is now FreeMonoTengwar, because its set has been carefully devised on these cretaria. So these signs should probably be added to all fonts if they are present in FreeMonoTengwar.

But one thing that may be noted is that these 3 signs can be (more or less) approximated to 1 dot+2dots+1dot / 2dots+2dots / 1dot+3dots+1dot , so there's a temporary solution for 'emulating' these signs (and that has been my preferred method in my tengwar modes up until now).

**Comment by laicasaane** [comment]
I'm emulating them at this time too. But it's better for them to be represented as a single unit. The combination of several dots may not look good because of their kerning and spacing.

I think this can be considered as a long term improvement, and can be done when you're going to make changes to the fonts (follow our earlier discussion).

**Comment by BenTalagan** [comment]
After a second look, are you sure about the middle one (squared pusta) ? I managed to find it only in Eldamar Alt but I could not find it in the FreeTengwarFont project mapping here :

http://freetengwar.sourceforge.net/mapping.html

Also, Everson's paper does not state that this specific sign is attested, see here at page 3 : 

 http://www.evertype.com/standards/iso10646/pdf/tengwar.pdf

My proposal is to add pusta signs `Quadruple Pusta` and `Quintuple pusta`, but maybe not the square one ?

**Comment by laicasaane** [comment]
Actually it isn't included in the Unicode tengwar block because it's been in another block already. 

> Additionally, there are two more Unicode punctuation marks that shall be used together with the tengwar:
> U+2e2c: SQUARED FOUR DOT PUNCTUATION (⸬)
> U+10fb: GEORGIAN PARAGRAPH SEPARATOR (჻)
> (copied from section 3 *Differences from Michael Everson’s 2001-03-07 Discussion Paper*

It's also used in Tolkien's own Tengwar handwriting of Namárie
http://at.mansbjorkman.net/teng_punctuation.htm

**Comment by laicasaane** [comment]
It turns out that we don't have this pusta either `჻`. Because the Dan Smith layout overlaps the standard one, so it's better to include those pustar in the fonts.

**Comment by laicasaane** [comment]
Johan Winge also states that all the pustar have been included in the Unicode already. So in the mapping table, they are marking as grey for being deprecated. I think this image is the best and most comprehensive reference that lists out all attested characters in the Tengwar writing system:
![image](https://user-images.githubusercontent.com/1594982/27009974-f82d55e2-4ec4-11e7-88f9-0e09beeea702.png)

**Comment by BenTalagan** [comment]
Thanks a lot for having checked this! I'll update the fonts accordingly, I'm slowly preparing this.

**Comment by BenTalagan** [comment]
Ok, 1.1.4 has arrived. It should address this issue 😃  (I let you check)

**Comment by laicasaane** [comment]
They look very well. 👍
