### ISSUE TITLE
Web browsers word-wrapping may break some words when using some tengwar fonts in certain circumstances

### ISSUE THREAD

**Issue by BenTalagan** [BenTalagan/glaemscribe#16]
A good example is better than an explanation ; with the currently merged annatar fonts, a word like lumbule would be transcribed : 

`な&w&j$`

because the ligatured lambe is mapped within the japanese unicode set, the word wrap breaking logic of web browsers will allow this word to be cut after the ligatured lambe at the end of a line.

Solution 1 (fastest) : change the mapping of incriminated characters. One good idea would probably to stick to tengwar elfica's mapping.

Solution 2 (painful, and a long work : but cool) : start migrating the old generation fonts to opentype with gsub and gpos tables, and use the free tengwar font project mapping .

**Comment by laicasaane** [comment]
Not just web browsers but word processors like LibreOffice also have this problem. Solution 2 would be better, not just cool.

**Comment by BenTalagan** [comment]
Certainly, agreed at 110% ! but this is huge work. It means redesigning completely all fonts : for example, this does not prevent from designing multiple versions of consonant modifiers because it's not just a matter of placement but also of size. This does not prevent to design ligatures as well & so on. 

Making a clean OpenType tengwar font is a lot of work with complex substitution/position rules if you want to handle complex cases beautifully, and this is what Mach Wust is actually trying to achieve with Telcontar - and he's struggling hard.

I'd rather have a temporary Solution 1 implemented quite quickly as a fix, and wait for the next generation of fonts to appear, and focus on other transcription/mode issues for the moment. The english modes are pulling a lot of energy from us (Bertrand & I) atm and it's our priority. :)

**Comment by laicasaane** [comment]
Instead of a OpenType layout with advanced things like gpos and gsub, we could just simply remap the current Dan Smith's layout to a custom layout that extends the standard layout used by Free Tengwar Font Project?

**Comment by pfstrack** [comment]
I vote for the simple solution. Bug fixes should be as simple as they can be to get the job done. Option 2 is an entirely separate project which, while interesting, should be prioritized based on what your current interests are.

**Comment by BenTalagan** [comment]
> Instead of an OpenType layout with advanced things like gpos and gsub, we could just simply remap the current Dan Smith's layout to a custom layout that extends the standard layout used by Free Tengwar Font Project?

This is a good transitional idea imho. **But** it still requires a lot of work because no normalization has been written yet ; in this norm there should be slots for e.g. multiple variants of the tehtar (most of fonts have 4 variants but this is purely arbitrary) plus variants of the inner signs for lambe, plus multiple variants of consonant modifiers, plus potential ligatures which are totally arbitrary too & so on. So it would be a little factorization nightmare, it should probably define base ranges for common features for the set of fonts we already have, but would also provide free ranges to give room for more exotic things specific to each font. 

For various reasons, it would be nice : first one being that glaemscribe fonts are diverging more and more from their original versions without any reference to stick to (in an ideal world, this would be the Free Tengwar Font Project). 

But I completely agree with Paul : even in this form, it would be an entire project, which aim would be "unifying currently existing Dan-Smith-layout-based tenwar fonts" - meaning it would also put the pressure on the original font authors who may have other things to do. So I'd rather stay in a minimal 'patching' & bug fix spirit at the moment with these old fonts, and watch for the evolution of the new generation fonts. All the more because there's a risk of breaking things in the fonts when doing too much patching (e.g. I'm quite mistrustful about hidden features like kerning ... )

**Comment by laicasaane** [comment]
Hi, it's been some time. I'm going to have some work with Tengwar yet again. Could you release the fix soon?

**Comment by BenTalagan** [comment]
Hi Laicasaane!

Sure. Sorry for the wait ; the release of the next version of the official glaemscrafu website has been delayed, since we've hit a difficult milestone linked to the english modes. Afterwhile, we (Bertrand Bellet & I) had both a heavy professional year, so tolkienic works had to stay on standby.

Since I'd rather synchronize the website and the github repo, what we are going to do is try to release a new version of the website as well as glaemscribe in the next few days, lighter than we had expected, and release the english modes later on during the year. 

That way, we can split the heavy work in multiple parts and be discharged of other matters that are not related at all to tengwar transcription (such as the update of the graphical chart of the website which I have slightly redesigned to use more modern and portable fonts). As well, there are a lot of small UX stuff that I had made to the official glaemscribe interface which I need to put online.

But anyway, **you can still have access to the latest changes I've made to the fonts which should fix the word wrap problems. They are available in the "TolkiensReadingDay2018" branch**. I don't have made any further changes to glaemscribe yet so you virtually have access to the latest version of glaemscribe if you're eager to work on your side :-) .

Cheers,
Ben

**Comment by laicasaane** [comment]
My bad, I didn't even look into the other branch! And yeah, I only concern the wordwrap issues in the next work so this fix is just sufficient. Thanks.

**Comment by BenTalagan** [comment]
Closed after 1.2.0 release.
