### ISSUE TITLE
Tengwar Eldamar GlaemUnicode doesn't stand alone

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#19]
When I install both Glaemscrafu and GlaemUnicode versions, they are listed as 1 family with 2 “Regular” font faces. So when I specified the font to be “Tengwar Eldamar GlaemUnicode” in the editor, it doesn't work.
![image](https://user-images.githubusercontent.com/1594982/45570260-3b064900-b88c-11e8-8a41-61cf5702bf1e.png)

However, there is no problem with Annatar and others.
![image](https://user-images.githubusercontent.com/1594982/45570337-7c96f400-b88c-11e8-90b2-2f3f02b4fb15.png)

**Comment by BenTalagan** [comment]
You're right the TTF seems to have the wrong name. It's strange since all of them are generated from the unhinted fonts. Will fix this ASAP (tonight). Thanks for noticing!

**Comment by BenTalagan** [comment]
Ok, should be fixed now in the unicode_font_remapping branch. It was a problem of duplicated keys in the SFD file. Thanks again :)

**Comment by BenTalagan** [comment]
Closed after 1.2.0 release.
