### ISSUE TITLE
IDE: Charset panel loses current font upon character addition

### ISSUE THREAD

**Issue by Omikhleia** [BenTalagan/glaemscribe#2]
IDE v1.0.0 in Firefox
When I add a new character in the charset panel (let's say, default charset is sarati_eldamar, and I add char "38" as "SARATI_P_FINAL"), the font in the charset panel switches back to roman (apparently no style attribute in the HTML).
Workaround: Just changing the font name back and forth refreshes the panel ;-)

**Comment by BenTalagan** [comment]
Fixed. Thanks for point out!
