### ISSUE TITLE
Four dots (U+2058) and tricolon (U+205D) appear incorrectly in printed document (pdf)

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#23]
This only happen when I use Microsoft Word and export pdf file from it. This doesn't happen with LibreOffice. (I only use Microsoft Print to PDF to export the pdf.)

This is in MS Word, the text appear correct
![Word-doc](https://user-images.githubusercontent.com/1594982/59760677-0ca31780-92bd-11e9-84fe-09ceecc06bc5.png)

This is the pdf I've exported
![Pdf-doc](https://user-images.githubusercontent.com/1594982/59760710-217fab00-92bd-11e9-8597-b15be356e7b6.png)

Elfica is wrong too, I've forgot to draw the rectangle around it.

**Comment by BenTalagan** [comment]
Strange! I don't know even know where to start on this one :-) Do you use the ttf fonts in fonts/build/ttfs (not those in fonts/src/ttf_exports) ?

**Comment by laicasaane** [comment]
> Do you use the ttf fonts in fonts/build/ttfs
I do.

Oh well, think about it, maybe this doesn't have anything to do with the fonts themselves. It could be a bug of MS Word. I'll try reporting this to them.

**Comment by BenTalagan** [comment]
Hi Laicassane, after looking closely to your screenshots,  it seems to me that the characters you have marked in rectangles are not the good ones. They don't have the good aspect. It's especially true for the diamond in Annatar, where the four dots should be more "squared", not round, and they should be closer too. So to my opinion, either the PDF export is wrong, or the PDF viewer cannot find these characters in the installed fonts, and it replaces them with the ones from another font (as web browsers usually do).

You could try to recheck your installed fonts and see if there's no problem (old fonts still present & clashing, and so on). You could also try to export your pdf with the "embed fonts" option.

**Comment by laicasaane** [comment]
Well, I've reported the problem to Microsoft.

FYI, I've tested the fonts in both MS Word and LibreOffice Writer and the pdf from LibreOffice doesn't have this issue.

This is the pdf from LibreOffice, using the same "Microsoft Print to PDF" printer.
![image](https://user-images.githubusercontent.com/1594982/59859819-b19a1f00-93a7-11e9-8a3d-a0c3590c12eb.png)

**Comment by BenTalagan** [comment]
Ok, I close the issue as "upstream" issue, but don't hesitate to report if you have some news. It might come from something implied in the build chain (maybe the autohint step, why not? I don't know), but I hope to transition one day to some more modern homemade fonts, so I don't feel it's a big problem. Have you tried to export with the "embed fonts" option ?

**Comment by laicasaane** [comment]
> Have you tried to export with the "embed fonts" option ?

Sadly, "export pdf" doesn't work with MS Word. All the tehtar would be messed up badly.

**Comment by BenTalagan** [comment]
Is the print preview correct ? If so, maybe you can try [PDF Creator](https://www.pdfforge.org/pdfcreator) (it is an alternate PDF printer). It's been a while since I've been working under windows but I remember a few years ago I'd prefer using that tool for PDF exports.

**Comment by laicasaane** [comment]
Well, the print preview is correct. And I've tried all other printers that I could find but the results are the same.

**Comment by BenTalagan** [comment]
It may be the same problem as this [bug report ](https://answers.microsoft.com/en-us/msoffice/forum/all/missing-characters-when-you-save-as-pdf-an-ms-word/7711709c-32a2-4c27-b402-9db327598a4e) ?

**Comment by laicasaane** [comment]
Could be, I don't know. I didn't copy the text from pdf file to make a comparision. (For clarity, I'm talking about the messed up tehtar.)
