### ISSUE TITLE
Error when try to load sessions which use FreeMonoTengwar or Tengwar Telcontar fonts

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#27]
I cannot load this saved session:
![image](https://user-images.githubusercontent.com/1594982/64698301-d4cafb00-d4cc-11e9-9b87-6420c9218a4a.png)

Console log:
![image](https://user-images.githubusercontent.com/1594982/64698260-c2e95800-d4cc-11e9-94fe-89982c462f20.png)

**Comment by BenTalagan** [comment]
Funny enough, it's a bug I've encountered a few days ago. I've fixed it locally but haven't pushed the fix yet. Just give me 5 minutes :)

**Comment by laicasaane** [comment]
It's now working as expected!

**Comment by BenTalagan** [comment]
Cool, thanks for the report!
