### ISSUE TITLE
\outspace doesn't support a sequence

### ISSUE THREAD

**Issue by davidfraser** [BenTalagan/glaemscribe#32]
I would like to use `\outspace` with a sequence of characters (`\outspace CIRTH_SPACE CIRTH_PUNCT_MID_DOT CIRTH_SPACE`) so there's a bit of space around the dot), which the [documentation says is supported](https://glaemscrafu.jrrvf.com/english/glaemscribe-mode-authoring.html#:~:text=You%20can%20change%20that%20behaviour%20by%20redefining%20the%20output%20space%20sequence%20in%20the%20mode%20options.) - however it doesn't work and I get:
```
Mode has some errors:

45: Element 'outspace' should have 1 arguments.
```

**Comment by BenTalagan** [comment]
Hi David,

Seems like the example in the doc is wrong. The glaeml language requires to separate the args (like in shell, using quotes & so on) and the outspace command requires 1 and only 1 arg. So the good solution should be to put your sequence into quotes :

```
\outspace CIRTH_SPACE CIRTH_PUNCT_MID_DOT CIRTH_SPACE```

Let me know if it solves your problem !

**Comment by davidfraser** [comment]
Yes that works fine! Thanks...
