### ISSUE TITLE
Wrong position of U+E054 in Tengwar Eldamar Glaemscrafu font

### ISSUE THREAD

**Issue by laicasaane** [BenTalagan/glaemscribe#8]
This is the comparision table between `Tengwar Eldamar Glaemscrafu` and `Tengwar Eldamar Alt`. Green cells are the expected results.
![2017-05-29_18-11-58](https://cloud.githubusercontent.com/assets/1594982/26547711/925f4fb0-449a-11e7-95ca-4b81256b2a86.png)

**Comment by BenTalagan** [comment]
I've just had a look. I've not added support yet for the backward accent, it's missing in the eldamar charset (and all other tengwar charsets). I should add support for this char but need to check other fonts. Generally speaking, it's better if you stick to the official charsets rather than using your own ones, because it will give you compliancy with all tengwar fonts in a row - but it's true, here you're blocked with that missing accent.

Keeping you informed.

**Comment by laicasaane** [comment]
I downloaded the charsets from your site and manually add these virtual characters: `TICK_TEHTA (THSUP_TICK_*)`, `TICK_TEHTA_REVERSED (THSUP_TICK_INV_*)`, `GRAVE_TEHTA (THINF_DSTROKE_*)` because your charsets don't have them. That's the only modifications I made.

**Comment by BenTalagan** [comment]
Good to know! I think TICK_TEHTA_REVERSED was already present but under the name A_TEHTA_CIRCUM but the other ones are truly missing. I'll add these, but need to check the font compatibility before, some may need patching.

Keeping you informed.

**Comment by laicasaane** [comment]
I updated the mode to use your name `A_TEHTA_CIRCUM`. ☺️

**Comment by BenTalagan** [comment]
Ok, so here a small update.

a) TICK_TEHTA is already present (it's A_TEHTA_CIRCUM).
b) All fonts have TICK_TEHTA_REVERSED, this one is easy, I'll update the charsets accordingly.
c) E_TEHTA_GRAVE is going to be a bit more tricky.
    - Elfica is ok (as usual!), but it has its own mapping.
    - Eldamar is ok, the version you were looking for is at U+2FFC (all tengwar in the personal use section are coming from Eldamar, not Eldamar + Alt).
    - Parmaite is ok, it has the same mapping as Eldamar.
    - Annatar is ok BUT it has a different mapping.
    - Sindarin is not ok (as usual :( )

So finally, the only font patching I have to do is for Tengwar Sindarin, to add all accents. I'll probably map them on Elfica's mapping.

**Comment by BenTalagan** [comment]
Ok, 1.1.4 has arrived. It should address this issue 😃
